client/urls.py
from django.urls import path
from . import views


app_name = 'client'

urlpatterns = [
    path('', views.ClientIndexView.as_view(), name='index'),
    path('lista/', views.ClientListView.as_view(), name='list'),
    path('<int:pk>/atualizacao/', views.ClientUpdateView.as_view(), name='update'),
    path('novo/', views.ClientCreateView.as_view(), name='new'),
    path('<int:pk>/detalhe/', views.ClientDetailView.as_view(), name='detail'),
    path('<int:pk>/exclusao/', views.ClientDeleteView.as_view(), name='delete'),
]

cliente/urls.py
from django.urls import path

from cliente import views

app_name = 'cliente'
urlpatterns = [
    path('lista/', views.ClienteListView.as_view(), name='lista'),
    path('cadastro/', views.ClienteCreateView.as_view(), name='cadastro'),
    path('<int:pk>/detalhes/', views.ClienteDetailView.as_view(), name='detalhes'),
    path('<int:pk>/atualizacao/', views.ClienteUpdateView.as_view(), name='atualizacao'),
    path('<int:pk>/exclusao/', views.ClienteDeleteView.as_view(), name='exclusao'),
]

quitandaDM/urls.py
from django.contrib import admin
from django.urls import include, path
from base import views

urlpatterns = [
    path('', views.HomePageViews.as_view(), name='home-page'),
    path('sobre/', views.SobrePageViews.as_view(), name='sobre'),
    path('cliente/', include('client.urls')),
    path('produto/', include('product.urls')),
    path('admin/', admin.site.urls),
]

cliente/models.py
from django.db import models


class Cliente(models.Model):
    SEXO = [
        ('F', 'Feminino'),
        ('M', 'Masculino'),
        ('I', 'Não definido')
    ]
    STATUS = [
        ('1', 'Em dia'),
        ('2', 'Mensal'),
        ('3', 'Devedor'),
    ]
    nome = models.CharField(max_length=256)
    sexo = models.CharField(max_length=1, choices=SEXO)
    data_nascimento = models.DateField('data de nascimento', blank=True, null=True)
    cidade = models.CharField(max_length=64, default='Teresina')
    bairro = models.CharField(max_length=64, default='Real Copagri')
    contato = models.CharField(max_length=16, blank=True, null=True)
    email = models.EmailField(max_length=64, blank=True, null=True)
    data_cadastro = models.DateField('data do cadastro', auto_now=True)
    foto = models.ImageField(upload_to='cliente_fotos', blank=True, null=True)
    cpf = models.CharField('CPF', max_length=32, blank=True, null=True, unique=True)
    data_ultima_compra = models.DateTimeField('data da última compra', null=True)
    status = models.CharField(max_length=1, choices=STATUS, default='3')


    def __str__(self):
        return self.nome

cliente/views.py
from django.urls import reverse_lazy
from django.views.generic import TemplateView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic.list import ListView
from cliente.models import Cliente


class ClienteDetailView(DetailView):
    model = Cliente

    def get_object(self, queryset=None):
        pk = self.kwargs.get(self.pk_url_kwarg)
        return Cliente.objects.get(pk=pk)


class ClienteListView(ListView):
    model = Cliente


class ClienteCreateView(CreateView):
    model = Cliente
    fields = ['nome', 'sexo', 'data_nascimento', 'cpf', 'cidade', 'bairro',
              'contato', 'email', 'status', 'foto']

    def get_success_url(self):
        return reverse_lazy('cliente:lista')


class ClienteUpdateView(UpdateView):
    model = Cliente
    fields = ['nome', 'sexo', 'data_nascimento', 'cpf', 'cidade', 'bairro',
              'contato', 'email', 'status', 'foto']

    def get_success_url(self):
        return reverse_lazy('cliente:lista')


class ClienteDeleteView(DeleteView):
    model = Cliente

    def get_success_url(self):
        return reverse_lazy('cliente:lista')

cliente/templates/cliente/cliente_confirm_delete.html
{% extends "base/base.html" %}

{% load static %}

{% block mstatics %}
<link href="{% static 'mcss/formularios.css' %}" rel="stylesheet">
{% endblock %}

{% block title %}Excluir produto{% endblock %}

{% block conteudo %}
<form class="confirma-exclusao" method="post">
    {% csrf_token %}
    <p>Você tem certeza que quer excluir {{ object }}?</p>
    {{ form }}
    <input type="submit" class="mbtn mbtn-excluir mbtn-gt" value="Excluir">
</form>
{% endblock %}

cliente/templates/cliente/cliente_detail.html
{% extends "base/base.html" %}
{% load static %}

{% block mstatics %}
<link href="{% static 'mcss/formularios.css' %}" rel="stylesheet">
{% endblock %}

{% block conteudo %}
<p>Nome: {{ object.nome }}</p>
<p>Sexo: {{ object.sexo }}</p>
<p>Data de nascimento: {{ object.data_nascimento }}</p>
<p>CPF: {{ object.cpf }}</p>
<p>Cidade: {{ object.cidade }}</p>
<p>Bairro: {{ object.bairro }}</p>
<p>Contato: {{ object.fone }}</p>
<p>Email: {{ object.email }}</p>
<p>Data do cadastro: {{ object.data_cadastro }}</p>
<p>Data da última compra: {{ object.data_ultima_compra }}</p>
<p>Status: {{ object.status }}</p>
<p>Foto: {{ object.foto }}</p>
<hr>
<a class="mbtn mbtn-atualizar mbtn-gt" href="{% url 'cliente:atualizacao' object.pk %}">Atualizar</a>
<a class="mbtn mbtn-excluir mbtn-gt" href="{% url 'cliente:exclusao' object.pk %}">Excluir</a>
{% endblock %}

cliente/templates/cliente/cliente_form.html
{% extends "base/base.html" %}
{% load static %}

{% block mstatics %}
<link href="{% static 'mcss/formularios.css' %}" rel="stylesheet">
{% endblock %}

{% block title%}Editar cliente{% endblock %}

{% block conteudo %}
<div>
  <form method="post">
    <div class="form-titulo">
      <h2>Editar cliente</h>
    </div>
    <div class="input-div">
      {% csrf_token %}
      {{ form.as_p }}
    </di>
    <div style="text-align: right">
      <button type="submit" class="mbtn mbtn-salvar mbtn-gt">Salvar</button>
    </div>
  </form>
</div>
{% endblock %}

cliente/templates/cliente/cliente_list.html
{% extends "base/base.html" %}

{% load static %}

{% block mstatics %}
<link href="{% static 'mcss/buscas.css' %}" rel="stylesheet">
<link href="{% static 'mcss/formularios.css' %}" rel="stylesheet">
<link href="{% static 'mcss/tabelas.css' %}" rel="stylesheet">
{% endblock %}

{% block conteudo %}
<p>{{ message }}</p>
<h1>Meus clientes</h1>
<div style="text-align: center">
<a class="mbtn mbtn-salvar mbtn-gt" href="{% url 'cliente:cadastro' %}">CADASTRAR NOVO CLIENTE</a>
<form class="mform" role="search">
  <input class="input-busca" type="search" placeholder="Buscar" aria-label="Search">
  <button class="mbtn-busca" type="submit">
    <img src="{% static '/img/searchicon.png' %}" width="32" height="32">
  </button>
</form>
</div>
<div class="mtabela">
  <table>
    <thead>
      <tr>
        <th scope="col">ID</th>
        <th scope="col">NOME</th>
        <th scope="col">CPF</th>
        <th scope="col">CONTATO</th>
        <th scope="col">E-MAIL</th>
        <th scope="col">DATA CADASTRO</th>
        <th scope="col">ÚLTIMA COMPRA</th>
        <th scope="col">STATUS</th>
        <th scope="col">AÇÃO</th>
      </tr>
    </thead>
    <tbody>
      {% for cliente in object_list %}
      <tr>
        <th scope="row">{{ cliente.id }}</th>
        <td>{{ cliente.nome }}</td>
        <td>{{ cliente.cpf }}</td>
        <td>{{ cliente.contato }}</td>
        <td>{{ cliente.email }}</td>
        <td>{{ cliente.data_cadastro }}</td>
        <td>{{ cliente.data_ultima_compra }}</td>
        <td>
          {% if cliente.status == '1' %}
          <span class="mbtn" style="color: black; background-color: green; border-radius: 50%">1</span>
          {% elif cliente.status == '2' %}
          <span class="mbtn" style="color: black; background-color: yellow; border-radius: 50%">2</span>
          {% else %}
          <span class="mbtn" style="color: black; background-color: red; border-radius: 50%">3</span>
          {% endif %}
        </td>
        <td>
          <a href="{% url 'cliente:detalhes' cliente.pk %}">
            <img src="{% static '/img/eyeglasses.svg' %}" alt="Exibir" width="40" height="40">
          </a>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}

cliente/templates/cliente/index.html
{% extends 'base/base.html' %}

{% block conteudo %}
<a href="{% url 'cliente:cadastro' %}" class="btn btn-primary btn-lg">Cadastrar novo cliente</a>
<p><a href="{% url 'cliente:lista' %}">Lista de clientes</a></p>
<p><a href="{% url 'cliente:cadastro' %}">Cadastrar novo cliente</a></p>
{% endblock %}
</body>
</html>