client/urls.py
from django.urls import path
from . import views


app_name = 'client'

urlpatterns = [
    path('', views.ClientIndexView.as_view(), name='index'),
    path('lista/', views.ClientListView.as_view(), name='list'),
    path('<int:pk>/atualizacao/', views.ClientUpdateView.as_view(), name='update'),
    path('novo/', views.ClientCreateView.as_view(), name='new'),
    path('<int:pk>/detalhe/', views.ClientDetailView.as_view(), name='detail'),
    path('<int:pk>/exclusao/', views.ClientDeleteView.as_view(), name='delete'),
]

quitandaDM/urls.py
from django.contrib import admin
from django.urls import include, path
from base import views

urlpatterns = [
    path('', views.HomePageViews.as_view(), name='home-page'),
    path('sobre/', views.SobrePageViews.as_view(), name='sobre'),
    path('cliente/', include('client.urls')),
    path('produto/', include('product.urls')),
    path('admin/', admin.site.urls),
]

client/models.py
from django.db import models


class Client(models.Model):

    GENDER = [
        ('F', 'Feminino'),
        ('M', 'Masculino'),
        ('I', 'Não definido')
    ]
    STATUS = [
        ('1', 'Em dia'),
        ('2', 'Mensal'),
        ('3', 'Devedor'),
    ]
    name = models.CharField('nome', max_length=256)
    gender = models.CharField('sexo', max_length=1, choices=GENDER)
    birth_date = models.DateField('data de nascimento', blank=True, null=True)
    city = models.CharField('cidade', max_length=64, default='Teresina')
    district = models.CharField('bairro', max_length=64, default='Real Copagri')
    contact = models.CharField('contato', max_length=16, blank=True, null=True)
    email = models.EmailField('e-mail', max_length=64, blank=True, null=True)
    registration_date = models.DateField('data do cadastro', auto_now=True)
    photo = models.ImageField('foto', upload_to='cliente_fotos', blank=True, null=True)
    cpf = models.CharField('CPF', max_length=32, blank=True, null=True, unique=True)
    last_purchase_date = models.DateTimeField('data da última compra', null=True)
    status = models.CharField(max_length=1, choices=STATUS, default='3')


    def __str__(self):
        return self.name

client/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView, DeleteView, DetailView, TemplateView, UpdateView
from django.views.generic.list import ListView
from .models import Client


class ClientIndexView(TemplateView):
    template_name = 'client/index.html'


class ClientListView(ListView):
    model = Client


class ClientUpdateView(UpdateView):
    model = Client

    fields = ['name', 'gender', 'birth_date', 'city', 'district', 'contact', 'email',
              'photo', 'cpf', 'last_purchase_date', 'status']
    

    def get_object(self, queryset=None):
        pk = self.kwargs.get(self.pk_url_kwarg)
        return Client.objects.get(pk=pk)
    
    
    def get_success_url(self):
        return reverse_lazy('client:list')
    

class ClientCreateView(CreateView):
    model = Client
    fields = ['name', 'gender', 'birth_date', 'city', 'district', 'contact', 'email',
              'photo', 'cpf', 'last_purchase_date', 'status']
    success_url = reverse_lazy("client:list")
 

class ClientDetailView(DetailView):
    model = Client


class ClientDeleteView(DeleteView):
    model = Client

    def get_success_url(self):
        return reverse_lazy('client:list')

client/templates/client/client_confirm_delete.html
{% extends "base/base.html" %}

{% load static %}

{% block mstatics %}
<link href="{% static 'mcss/formularios.css' %}" rel="stylesheet">
{% endblock %}

{% block title %}Excluir produto{% endblock %}

{% block conteudo %}
<form class="confirma-exclusao" method="post">
    {% csrf_token %}
    <p>Você tem certeza que quer excluir {{ object }}?</p>
    {{ form }}
    <input type="submit" class="mbtn mbtn-excluir mbtn-gt" value="Excluir">
</form>
{% endblock %}

client/templates/client/client_detail.html
{% extends "base/base.html" %}
{% load static %}

{% block mstatics %}
<link href="{% static 'mcss/formularios.css' %}" rel="stylesheet">
{% endblock %}

{% block conteudo %}
<p>Nome: {{ object.name }}</p>
<p>Sexo: {{ object.gender }}</p>
<p>Data de nascimento: {{ object.birth_date }}</p>
<p>Bairro: {{ object.district }}</p>
<p>Contato: {{ object.contact }}</p>
<p>E-mail: {{ object.email }}</p>
<p>Data de registro: {{ object.registration_date }}</p>
<p>CPF: {{ object.cpf }}</p>
<p>Data da última compra: {{ object.last_purchase_date }}</p>
<p>Status: {{ object.status }}</p>
<p>Foto: {{ object.photo }}</p>
<hr>
<a class="mbtn mbtn-atualizar mbtn-gt" href="{% url 'client:update' object.pk %}">Atualizar</a>
<a class="mbtn mbtn-excluir mbtn-gt" href="{% url 'client:delete' object.pk %}">Excluir</a>
{% endblock %}

client/templates/client/client_form.html
{% extends "base/base.html" %}
{% load static %}

{% block mstatics %}
<link href="{% static 'mcss/formularios.css' %}" rel="stylesheet">
{% endblock %}

{% block title%}Editar cliente{% endblock %}

{% block conteudo %}
<div>
  <form method="post">
    <div class="form-titulo">
      <h2>Editar cliente</h>
    </div>
    <div class="input-div">
      {% csrf_token %}
      {{ form.as_p }}
    </di>
    <div style="text-align: right">
      <button type="submit" class="mbtn mbtn-salvar mbtn-gt">Salvar</button>
    </div>
  </form>
</div>
{% endblock %}

client/templates/client/client_list.html
{% extends 'base/base.html' %}
{% block conteudo %}
  <p>{{ message }}</p>
  <ul>
    {% for client in object_list %}
      <li>
        <a href="{% url 'client:detail' client.pk %}">{{ client }}</a>
      </li>
      {% empty %}
      <li>
        Nenhum cliente cadastrado!
      </li>
    {% endfor %}
    <li>
        <a class="btn btn-secondary btn-lg" role="button" href="{% url 'client:new' %}">Cadastrar novo cliente</a>
    </li>
  </ul>
{% endblock %}

client/templates/client/index.html
{% extends 'base/base.html' %}

{% block conteudo %}
<p><a href="{% url 'client:list' %}">Lista de clientes</a></p>
<p><a href="{% url 'client:new' %}">Cadastrar novo cliente</a></p>
{% endblock %}
</body>
</html>