client/urls.py
from django.urls import path
from . import views


app_name = 'client'

urlpatterns = [
    path('', views.ClientIndexView.as_view(), name='index'),
    path('lista/', views.ClientListView.as_view(), name='list'),
    path('<int:pk>/atualizacao/', views.ClientUpdateView.as_view(), name='update'),
    path('novo/', views.ClientCreateView.as_view(), name='new'),
    path('<int:pk>/detalhe/', views.ClientDetailView.as_view(), name='detail'),
    path('<int:pk>/exclusao/', views.ClientDeleteView.as_view(), name='delete'),
]

product/urls.py
from django.urls import path
from . import views


app_name = 'product'
urlpatterns = [
    path('', views.IndexPageView.as_view(), name='index'),
    path('lista/', views.ProductListView.as_view(), name='list'),
    path('cadastro/', views.ProductCreateView.as_view(), name='create'),
    path('<int:pk>/detalhe/', views.ProductDetailView.as_view(), name='detail'),
    path('<int:pk>/atualizacao', views.ProductUpdateView.as_view(), name='update'),
    path('<int:pk>/exclusao', views.ProductDeleteView.as_view(), name='delete'),
]

quitandaDM/urls.py
from django.contrib import admin
from django.urls import include, path
from base import views

urlpatterns = [
    path('', views.HomePageViews.as_view(), name='home-page'),
    path('sobre/', views.SobrePageViews.as_view(), name='sobre'),
    path('cliente/', include('client.urls')),
    path('produto/', include('product.urls')),
    path('admin/', admin.site.urls),
]

product/models.py
from django.db import models


class Product(models.Model):
    code = models.CharField("Código", max_length=32, unique=True)
    name = models.CharField("Nome", max_length=64, unique=True)
    manufacturer = models.CharField("Fabricante", max_length=64, null=True)
    description = models.TextField("Descrição", max_length=128, null=True)
    price = models.DecimalField("Preço", max_digits=8, decimal_places=2)
    registration_date = models.DateField("Data do cadastro", auto_now_add=True)
    manufacturing_date = models.DateField("Data de fabricação", null=True)

    class Meta:
        ordering = ['name']
        verbose_name = 'produto'

    def __str__(self):
        return self.name

product/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView, DeleteView, TemplateView, UpdateView
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView

from product.models import Product


class IndexPageView(TemplateView):
    template_name = 'product/index.html'


class ProductListView(ListView):
    model = Product


class ProductCreateView(CreateView):
    model = Product


class ProductDetailView(DetailView):
    model = Product

    def get_object(self, queryset=None):
        pk = self.kwargs.get(self.pk_url_kwarg)
        return Product.objects.get(id=pk)
    

class ProductUpdateView(UpdateView):
    model = Product
    fields = ['code', 'name', 'manufacturer', 'description', 'price', 'manufacturing_date']
    success_url = reverse_lazy("product:list")

class ProductDeleteView(DeleteView):
    model = Product
    success_url = reverse_lazy("product:list")

product/templates/product/index.html
{% extends "base/base.html" %}

{% block title %} quitandaDM - Home {% endblock %}
{% block conteudo %}
<a href="{% url 'product:list' %}">Lista de produtos</a><br>
<a href="{% url 'product:create' %}">Cadastrar novo produto</a><br>
{% endblock %}

product/templates/product/product.html
{% extends "base/base.html" %}
{% block conteudo %}
<form action="{% url 'app:produto' produto.id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend><h1>{{ produto.nome }}</h1></legend>
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        {% for
    </fieldset>
</form>
{% endblock %}

product/templates/product/product_confirm_delete.html
{% extends "base/base.html" %}

{% block title %}Excluir produto{% endblock %}

{% block conteudo %}
<form method="post">
    {% csrf_token %}
    <p>Você tem certeza que quer excluir {{ object }}?</p>
    {{ form }}
    <input type="submit" value="Excluir">
</form>
{% endblock %}

product/templates/product/product_detail.html
{% extends "base/base.html" %}

{% block conteudo %}
<p>Código: {{ object.code }}</p>
<p>Nome do produto: {{ object.name }}</p>
<p>Preço (R$): {{ object.price }}</p>
<p>Descrição: {{ object.description }}</p>
<p>Data de cadastro: {{ object.registration_date }}</p>
<p>Data de fabricação: {{ object.manufacturing_date }}</p>
<hr>
<a href="{% url 'product:update' object.pk %}">Atualizar produto</a><br>
<a href="{% url 'product:delete' object.pk %}">Excluir produto</a><br>
{% endblock %}

product/templates/product/product_form.html
{% extends "base/base.html" %}

{% block title%}Editar produto{% endblock %}

{% block conteudo %}

<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit" class="btn btn-primary">Salvar</button>
</form>
{% endblock %}

product/templates/product/product_list.html
{% extends "base/base.html" %}
{% block conteudo %}
<p>{{ message }}</p>
<ul>
{% for product in object_list %}
    <li>
        <a href="{% url 'product:detail' product.pk %}">{{ product }}</a>
    </li>
{% empty %}
    <p>Nenhum produto cadastrado!</p>
    <p><a class="btn btn-secondary btn-lg" role="button" href="{% url 'produto:cadastrar' %}">Cadastrar produto</a></p>
{% endfor %}
</ul>
{% endblock %}