client/urls.py
from django.urls import path
from . import views


app_name = 'client'

urlpatterns = [
    path('', views.ClientIndexView.as_view(), name='index'),
    path('lista/', views.ClientListView.as_view(), name='list'),
    path('<int:pk>/atualizacao/', views.ClientUpdateView.as_view(), name='update'),
    path('novo/', views.ClientCreateView.as_view(), name='new'),
    path('<int:pk>/detalhe/', views.ClientDetailView.as_view(), name='detail'),
    path('<int:pk>/exclusao/', views.ClientDeleteView.as_view(), name='delete'),
]

product/urls.py
from django.urls import path
from . import views


app_name = 'product'
urlpatterns = [
    path('', views.IndexPageView.as_view(), name='index'),
    path('lista/', views.ProductListView.as_view(), name='list'),
    path('cadastro/', views.ProductCreateView.as_view(), name='create'),
    path('<int:pk>/detalhe/', views.ProductDetailView.as_view(), name='detail'),
    path('<int:pk>/atualizacao', views.ProductUpdateView.as_view(), name='update'),
    path('<int:pk>/exclusao', views.ProductDeleteView.as_view(), name='delete'),
]

quitandaDM/urls.py
from django.contrib import admin
from django.urls import include, path
from base import views

urlpatterns = [
    path('', views.HomePageViews.as_view(), name='home-page'),
    path('sobre/', views.SobrePageViews.as_view(), name='sobre'),
    path('cliente/', include('client.urls')),
    path('produto/', include('product.urls')),
    path('admin/', admin.site.urls),
]

base/views.py
from django.views.generic import TemplateView


# Create your views here.

class HomePageViews(TemplateView):
    template_name = 'base/home.html'


class SobrePageViews(TemplateView):
    template_name = 'base/sobre.html'

base/templates/base/base.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <title>{% block title %}quitandaDm{% endblock %}</title>
    <link href="{% static 'mcss/principal.css' %}" rel="stylesheet">
    {% block mstatics %}{% endblock %}
    <title>Title</title>
</head>

<style>
.item {
    background-color: #fff;
    margin: 4px;
}
.menu {
    background-color: #333;
    color: white;
}
.coluna {
    display: grid;
    grid-template-columns: 2fr 8fr 1fr;
}
    
.linha {
    grid-template-rows: auto;
}
    
.rodape {
    background-color: blue;
    height: 50px;
    color: white;
    text-align: center;
}
</style>
<body>
<section class="navegacao">
    <nav>
        <ul>
            <li>
                <a aria-current="page" href="{% url 'home-page' %}">HOME</a>
            </li>
            <li>
                <a aria-current="page" href="#">VENDAS</a>
            </li>
            <li>
                <a aria-current="page" href="{% url 'product:index' %}">PRODUTOS</a>
            </li>
            <li>
                <a aria-current="page" href="{% url 'client:list' %}">CLIENTES</a>
            </li>
            <li>
                <a aria-current="page" href="#">ESTOQUE</a>
            </li>
            <li>
                <a aria-current="page" href="#">FORNECEDORES</a>
            </li>
            <li style="float:right">
                <a class="active" href="{% url 'sobre' %}" aria-current="page" href="#">SOBRE</a>
            </li>
        </ul>
    </nav>
</section>
<div class="coluna linha">
    <section class="item menu">
        MENU ESQUERDO
    </section>
    <section class="item conteudo">
        <div>
            {% block conteudo %}{% endblock %}
        </div>
    </section>
    <section class="item menu">
        Menu direito
    </section>
</div>

<section class="rodape">
    Rodapé
  </section>
</body>
</html>

base/templates/base/home.html
{% extends 'base/base.html' %}

{% block conteudo %}
<p>Em construção...</p>
{% endblock %}

base/templates/base/sobre.html
<style>
.navegacao {
  background-color: black;
  color: white;
  margin: 8px;
  height: 50px;
  border-radius: 8px;
  text-align: center;
}
.item {
  margin: 5px;
  background-color: red;
  text-align: center;
  font-size: 25px;
  border-radius: 10px;
  color: white;
}

.titulo {
  color: red;
  text-align: center;
}

.coluna {
  display: grid;
  grid-template-columns: 2fr 5fr 1fr;
}

.linha {
  grid-template-rows: auto;
}

.rodape {
  background-color: blue;
  height: 50px;
  color: white;
  text-align: center;
}

</style>
<section class="navegacao">
  Navegação
</section>
<section class="coluna linha">
  <div class="item">Menu direito</div>
  <div class="item">Conteúdo</div>
  <div class="item">Menu esquerdo</div>
</section>
<section class="rodape">
  Rodapé
</section>